services:
  web:
    build:
      context: ./
      dockerfile: read_it/Dockerfile
    restart: on-failure
    ports:
      - "${WEB_APP_PORT}:80"
    env_file: .env

  db:
    image: postgres:14
    ports:
      - "${POSTGRES_HOST}:${POSTGRES_PORT}:5432"
    volumes:
      - "${POSTGRES_DIR}:/var/lib/postgresql/data"
    env_file: .env
