# Generated by Django 4.2.5 on 2023-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "debug"),
                            ("info", "info"),
                            ("warning", "warning"),
                            ("error", "error"),
                            ("critical", "critical"),
                        ]
                    ),
                ),
                ("path", models.CharField()),
                ("message", models.TextField()),
            ],
            options={
                "db_table": "log",
            },
        ),
    ]
