# Generated by Django 4.2.5 on 2023-10-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodreadsScrapingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(max_length=200)),
                ("http_status_code", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("headers", models.TextField()),
                ("website_content", models.TextField()),
            ],
            options={
                "db_table": "goodreads_scraping_result",
            },
        ),
    ]
