# Generated by Django 4.2.5 on 2023-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodreads_scraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodreadsscrapingresult",
            name="parsed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="goodreadsscrapingresult",
            name="parser_version",
            field=models.IntegerField(null=True),
        ),
    ]
