# Generated by Django 4.2.5 on 2023-11-12 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read_it", "0004_rename_goodreads_scraping_result_book_goodreads_book_page"),
        ("goodreads_scraping", "0002_goodreadsscrapingresult_parsed_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GoodreadsScrapingResult",
            new_name="GoodreadsBookPage",
        ),
        migrations.AlterModelTable(
            name="goodreadsbookpage",
            table="goodreads_book_page",
        ),
    ]
