# Generated by Django 4.2.5 on 2023-11-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "goodreads_scraping",
            "0003_rename_goodreadsscrapingresult_goodreadsbookpage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodreadsAuthorPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(max_length=200)),
                ("http_status_code", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("headers", models.TextField()),
                ("website_content", models.TextField()),
                ("parser_version", models.IntegerField(null=True)),
                ("parsed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "goodreads_author_page",
            },
        ),
        migrations.CreateModel(
            name="GoodreadsBookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodreads_scraping.goodreadsauthorpage",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodreads_scraping.goodreadsbookpage",
                    ),
                ),
            ],
            options={
                "db_table": "goodreads_book_author",
            },
        ),
        migrations.AddField(
            model_name="goodreadsbookpage",
            name="authors",
            field=models.ManyToManyField(
                through="goodreads_scraping.GoodreadsBookAuthor",
                to="goodreads_scraping.goodreadsauthorpage",
            ),
        ),
    ]
