# Generated by Django 4.2.5 on 2023-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodreads_scraping", "0004_goodreadsauthorpage_goodreadsbookauthor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodreadsauthorpage",
            name="url",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="goodreadsbookpage",
            name="url",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
