# Generated by Django 4.2.5 on 2023-12-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads_scraping', '0005_alter_goodreadsauthorpage_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodreadsbookpage',
            name='parser_version',
            field=models.IntegerField(default=0),
        ),
    ]
