# Generated by Django 4.2.5 on 2023-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_it', '0004_rename_goodreads_scraping_result_book_goodreads_book_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middle_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
