name: Deploy to production

env:
  PYTHON_VERSION: '3.10'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: SSH to the server, pull the newest branch, install dependencies and run the gunicorn service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: | 
            cd ${{ secrets.DEPLOY_SOURCE_PATH }}
            rm -rf read-it
            git clone --depth=1 --branch=main https://github.com/wdebsqi/read-it.git
            cd read-it
            docker compose down
            docker rmi -f $(docker images -aq)
            docker compose up -d
            python3 manage.py migrate

